# frozen_string_literal: true

FactoryBot.define do
  factory :ai_request do
    association :profile
    prompt { 'Create a SMART goal to exercise more' }
    job_type { 'smart_goal' }
    status { 'pending' }
    # hash_value will be auto-generated by the model callback
  end

  trait :prioritization do
    prompt { 'Prioritize my tasks: exercise, work, sleep' }
    job_type { 'prioritization' }
  end

  trait :smart_goal do
    prompt { 'Create a SMART goal to learn Spanish' }
    job_type { 'smart_goal' }
  end
end
